### ISSUE TITLE
Adjust GetObjectRetention gateway endpoint (object retention)

### ISSUE THREAD

**Issue by amwolff** [storj/edge#451] opened 2024-07-10 14:22 UTC
This is an issue corresponding to #428, representing the work to complete adjustments to the GetObjectRetention gateway endpoint in the agreed scope of the Object Lock implementation.

**Comment by VitaliiShpital** [comment] 2024-07-25 11:53
actually the above change is almost a duplicate of @wilfred-asomanii's change here
https://review.dev.storj.io/c/storj/gateway/+/13967/4

I abandoned my change since there are already some reviews

**Closed** 2024-08-15 11:47 UTC
Labels: edge
